# Generated by Django 3.0.5 on 2020-04-15 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='address',
        ),
        migrations.AddField(
            model_name='orders',
            name='address1',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='orders',
            name='address2',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='orders',
            name='country',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='orders',
            name='phone',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='orders',
            name='city',
            field=models.CharField(default='', max_length=90),
        ),
        migrations.AlterField(
            model_name='orders',
            name='state',
            field=models.CharField(default='', max_length=90),
        ),
        migrations.AlterField(
            model_name='orders',
            name='zip_code',
            field=models.CharField(default='', max_length=90),
        ),
    ]
