# Generated by Django 3.0.5 on 2020-04-15 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20200415_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='address2',
        ),
    ]
